### ISSUE TITLE
setup firebase emulator

### ISSUE THREAD

**Issue by ArnaudPoletto** [Alvaro2112/Money_run#55]

**Comment by karimassi** [comment]
@ArnaudPoletto why did you move this to "Done in sprint 1" ? Since you finished it just now, please move it to "Done in sprint 2". 

Tagging others to notify them: please make sure that the items you complete are moved in the correct sprint column. We are currently in **sprint 2**. 

@RafaelRamirezS @Alvaro2112  @Tesa27 @gauthierboeshertz @Warhedgehog

**Comment by ArnaudPoletto** [comment]
Fixed, thank you.
